import os
from datetime import date, timedelta
from decimal import Decimal
from django.core.management.base import BaseCommand
from django.conf import settings
from vehicles.models import (
    Vehicle,
    VehicleImage,
    VehicleType,
    VehicleStatus,
    Transmission,
    FuelType,
)

try:
    from PIL import Image, ImageDraw, ImageFont
    HAS_PILLOW = True
except ImportError:
    HAS_PILLOW = False


def create_placeholder_image(filename: str, title: str, subtitle: str, color_hex: str) -> str:
    """Generate a clean sample banner image for seeded vehicles."""
    if not HAS_PILLOW:
        return ""

    vehicles_media_dir = os.path.join(settings.MEDIA_ROOT, "vehicles")
    os.makedirs(vehicles_media_dir, exist_ok=True)
    file_path = os.path.join(vehicles_media_dir, filename)

    if os.path.exists(file_path):
        return f"vehicles/{filename}"

    width, height = 800, 500
    img = Image.new("RGB", (width, height), color=color_hex)
    draw = ImageDraw.Draw(img)

    # Draw modern inner card rectangle
    draw.rectangle([30, 30, width - 30, height - 30], outline=(255, 255, 255), width=3)
    draw.rectangle([50, 50, width - 50, height - 50], fill=(0, 0, 0, 40))

    # Add text banner
    text_content = f"{title.upper()}\n{subtitle}\nEasy Rental Verified"
    draw.text((70, 180), text_content, fill=(255, 255, 255))

    img.save(file_path, "JPEG", quality=85)
    return f"vehicles/{filename}"


VEHICLES_SEED_DATA = [
    # ── Cycles ─────────────────────────────────────────────────────────────
    {
        "name": "Trek Marlin 7 Mountain Bike",
        "brand": "Trek",
        "model": "Marlin 7",
        "year": 2023,
        "color": "Matte Nautical Navy",
        "registration_number": "CYC-KTM-001",
        "vehicle_type": VehicleType.CYCLE,
        "transmission": Transmission.MANUAL,
        "fuel_type": FuelType.PETROL,
        "seats": 1,
        "luggage_capacity_kg": Decimal("15.00"),
        "odometer_km": 120,
        "price_per_day": Decimal("800.00"),
        "price_per_hour": Decimal("150.00"),
        "security_deposit": Decimal("2000.00"),
        "has_gps": False,
        "pickup_location": "Thamel, Kathmandu",
        "description": "Premium cross-country mountain bicycle with RockShox suspension, hydraulic disc brakes, and 1x10 Shimano Deore drivetrain. Perfect for Valley trails and city commutes.",
        "image_file": "trek_marlin_7.jpg",
        "bg_color": "#1e3d59",
    },
    {
        "name": "Giant Talon E+ Electric Mountain Bike",
        "brand": "Giant",
        "model": "Talon E+",
        "year": 2024,
        "color": "Amber Glow",
        "registration_number": "CYC-PKR-002",
        "vehicle_type": VehicleType.CYCLE,
        "transmission": Transmission.AUTOMATIC,
        "fuel_type": FuelType.ELECTRIC,
        "battery_range_km": 90,
        "top_speed_kmph": 32,
        "seats": 1,
        "luggage_capacity_kg": Decimal("20.00"),
        "odometer_km": 350,
        "price_per_day": Decimal("1500.00"),
        "price_per_hour": Decimal("250.00"),
        "security_deposit": Decimal("5000.00"),
        "has_gps": True,
        "has_usb_charger": True,
        "pickup_location": "Lakeside, Pokhara",
        "description": "High-performance electric trail cycle powered by SyncDrive Core motor with 500Wh EnergyPak battery. Effortlessly conquer Sarangkot and Peace Pagoda climbs.",
        "image_file": "giant_talon_e.jpg",
        "bg_color": "#ff6e40",
    },

    # ── Scooters ───────────────────────────────────────────────────────────
    {
        "name": "Honda Activa 6G",
        "brand": "Honda",
        "model": "Activa 6G DLX",
        "year": 2023,
        "color": "Decent Blue Metallic",
        "registration_number": "BA-99-PA-1101",
        "vehicle_type": VehicleType.SCOOTER,
        "transmission": Transmission.AUTOMATIC,
        "fuel_type": FuelType.PETROL,
        "engine_cc": 109,
        "mileage_kmpl": Decimal("55.00"),
        "horsepower": 8,
        "torque_nm": Decimal("8.84"),
        "top_speed_kmph": 85,
        "seats": 2,
        "luggage_capacity_kg": Decimal("18.00"),
        "fuel_tank_capacity_l": Decimal("5.30"),
        "odometer_km": 8500,
        "price_per_day": Decimal("1000.00"),
        "price_per_hour": Decimal("200.00"),
        "security_deposit": Decimal("3000.00"),
        "has_usb_charger": True,
        "pickup_location": "New Baneshwor, Kathmandu",
        "description": "Reliable and fuel-efficient automatic scooter, ideal for navigating city traffic and day-to-day sightseeing around Kathmandu.",
        "image_file": "honda_activa_6g.jpg",
        "bg_color": "#17b978",
    },
    {
        "name": "TVS NTORQ 125 Race Edition",
        "brand": "TVS",
        "model": "NTORQ 125 Race Edition",
        "year": 2024,
        "color": "Combat Red & Black",
        "registration_number": "BA-88-PA-4422",
        "vehicle_type": VehicleType.SCOOTER,
        "transmission": Transmission.AUTOMATIC,
        "fuel_type": FuelType.PETROL,
        "engine_cc": 124,
        "mileage_kmpl": Decimal("45.00"),
        "horsepower": 9,
        "torque_nm": Decimal("10.50"),
        "top_speed_kmph": 95,
        "seats": 2,
        "luggage_capacity_kg": Decimal("22.00"),
        "fuel_tank_capacity_l": Decimal("5.80"),
        "odometer_km": 4200,
        "price_per_day": Decimal("1200.00"),
        "price_per_hour": Decimal("220.00"),
        "security_deposit": Decimal("3500.00"),
        "has_bluetooth": True,
        "has_usb_charger": True,
        "pickup_location": "Jawalakhel, Lalitpur",
        "description": "Sporty scooter equipped with SmartXonnect Bluetooth console, navigation assist, and crisp acceleration for spirited city rides.",
        "image_file": "tvs_ntorq_125.jpg",
        "bg_color": "#d72323",
    },
    {
        "name": "Ather 450X Gen 3 Electric Scooter",
        "brand": "Ather",
        "model": "450X Gen 3",
        "year": 2024,
        "color": "Space Grey",
        "registration_number": "BA-01-PA-7890",
        "vehicle_type": VehicleType.SCOOTER,
        "transmission": Transmission.AUTOMATIC,
        "fuel_type": FuelType.ELECTRIC,
        "battery_range_km": 146,
        "horsepower": 8,
        "torque_nm": Decimal("26.00"),
        "top_speed_kmph": 90,
        "seats": 2,
        "luggage_capacity_kg": Decimal("22.00"),
        "odometer_km": 2100,
        "price_per_day": Decimal("1400.00"),
        "price_per_hour": Decimal("250.00"),
        "security_deposit": Decimal("4000.00"),
        "has_gps": True,
        "has_bluetooth": True,
        "has_usb_charger": True,
        "pickup_location": "Jhamsikhel, Lalitpur",
        "description": "Smart electric scooter with touchscreen navigation, instant torque, warp drive mode, and zero emissions.",
        "image_file": "ather_450x.jpg",
        "bg_color": "#303841",
    },

    # ── Motorcycles ────────────────────────────────────────────────────────
    {
        "name": "Royal Enfield Classic 350 Reborn",
        "brand": "Royal Enfield",
        "model": "Classic 350",
        "year": 2023,
        "color": "Gunmetal Grey",
        "registration_number": "BA-02-PA-3501",
        "vehicle_type": VehicleType.MOTORCYCLE,
        "transmission": Transmission.MANUAL,
        "fuel_type": FuelType.PETROL,
        "engine_cc": 349,
        "mileage_kmpl": Decimal("36.00"),
        "horsepower": 20,
        "torque_nm": Decimal("27.00"),
        "top_speed_kmph": 115,
        "seats": 2,
        "luggage_capacity_kg": Decimal("30.00"),
        "fuel_tank_capacity_l": Decimal("13.00"),
        "odometer_km": 9400,
        "price_per_day": Decimal("2500.00"),
        "price_per_hour": Decimal("400.00"),
        "security_deposit": Decimal("7000.00"),
        "has_usb_charger": True,
        "pickup_location": "Lakeside, Pokhara",
        "description": "Iconic cruiser with the smooth J-series engine, dual-channel ABS, and timeless thump. Perfect for Pokhara and Mustang highway touring.",
        "image_file": "royal_enfield_classic_350.jpg",
        "bg_color": "#3f4441",
    },
    {
        "name": "Royal Enfield Himalayan 450",
        "brand": "Royal Enfield",
        "model": "Himalayan 450",
        "year": 2024,
        "color": "Kamet White",
        "registration_number": "BA-03-PA-4502",
        "vehicle_type": VehicleType.MOTORCYCLE,
        "transmission": Transmission.MANUAL,
        "fuel_type": FuelType.PETROL,
        "engine_cc": 452,
        "mileage_kmpl": Decimal("30.00"),
        "horsepower": 40,
        "torque_nm": Decimal("40.00"),
        "top_speed_kmph": 150,
        "seats": 2,
        "luggage_capacity_kg": Decimal("45.00"),
        "fuel_tank_capacity_l": Decimal("17.00"),
        "odometer_km": 3200,
        "price_per_day": Decimal("3500.00"),
        "price_per_hour": Decimal("600.00"),
        "security_deposit": Decimal("10000.00"),
        "has_gps": True,
        "has_bluetooth": True,
        "has_usb_charger": True,
        "pickup_location": "Boudha, Kathmandu",
        "description": "Built for the Himalayas with liquid-cooled Sherpa engine, upside-down Showa forks, Google Maps integrated TFT screen, and long-travel suspension.",
        "image_file": "royal_enfield_himalayan_450.jpg",
        "bg_color": "#222831",
    },
    {
        "name": "Yamaha MT-15 V2",
        "brand": "Yamaha",
        "model": "MT-15 V2 Deluxe",
        "year": 2024,
        "color": "Metallic Black",
        "registration_number": "BA-04-PA-1503",
        "vehicle_type": VehicleType.MOTORCYCLE,
        "transmission": Transmission.MANUAL,
        "fuel_type": FuelType.PETROL,
        "engine_cc": 155,
        "mileage_kmpl": Decimal("48.00"),
        "horsepower": 18,
        "torque_nm": Decimal("14.10"),
        "top_speed_kmph": 130,
        "seats": 2,
        "luggage_capacity_kg": Decimal("15.00"),
        "fuel_tank_capacity_l": Decimal("10.00"),
        "odometer_km": 5100,
        "price_per_day": Decimal("1800.00"),
        "price_per_hour": Decimal("300.00"),
        "security_deposit": Decimal("5000.00"),
        "has_bluetooth": True,
        "pickup_location": "Koteshwor, Kathmandu",
        "description": "Aggressive streetfighter with Variable Valve Actuation (VVA), assist & slipper clutch, and golden USD front forks.",
        "image_file": "yamaha_mt_15.jpg",
        "bg_color": "#00204a",
    },
    {
        "name": "Bajaj Pulsar NS200 ABS",
        "brand": "Bajaj",
        "model": "Pulsar NS200",
        "year": 2023,
        "color": "Burnt Red",
        "registration_number": "BA-05-PA-2004",
        "vehicle_type": VehicleType.MOTORCYCLE,
        "transmission": Transmission.MANUAL,
        "fuel_type": FuelType.PETROL,
        "engine_cc": 199,
        "mileage_kmpl": Decimal("38.00"),
        "horsepower": 24,
        "torque_nm": Decimal("18.70"),
        "top_speed_kmph": 136,
        "seats": 2,
        "luggage_capacity_kg": Decimal("20.00"),
        "fuel_tank_capacity_l": Decimal("12.00"),
        "odometer_km": 11000,
        "price_per_day": Decimal("1600.00"),
        "price_per_hour": Decimal("280.00"),
        "security_deposit": Decimal("4500.00"),
        "pickup_location": "Sauraha, Chitwan",
        "description": "Proven 200cc perimeter frame naked bike with triple-spark DTS-i liquid-cooled engine for highway and city rides.",
        "image_file": "bajaj_pulsar_ns200.jpg",
        "bg_color": "#8c0000",
    },

    # ── Cars ───────────────────────────────────────────────────────────────
    {
        "name": "Hyundai Creta SX (O) Automatic",
        "brand": "Hyundai",
        "model": "Creta SX(O)",
        "year": 2024,
        "color": "Titan Grey",
        "registration_number": "BA-12-CHA-5501",
        "vehicle_type": VehicleType.CAR,
        "transmission": Transmission.AUTOMATIC,
        "fuel_type": FuelType.PETROL,
        "engine_cc": 1497,
        "mileage_kmpl": Decimal("17.00"),
        "horsepower": 115,
        "torque_nm": Decimal("144.00"),
        "top_speed_kmph": 170,
        "seats": 5,
        "luggage_capacity_kg": Decimal("433.00"),
        "fuel_tank_capacity_l": Decimal("50.00"),
        "odometer_km": 12500,
        "price_per_day": Decimal("7500.00"),
        "price_per_hour": Decimal("1000.00"),
        "security_deposit": Decimal("20000.00"),
        "has_ac": True,
        "has_gps": True,
        "has_bluetooth": True,
        "has_usb_charger": True,
        "has_child_seat": True,
        "pickup_location": "Tribhuvan International Airport, Kathmandu",
        "description": "Flagship 5-seater compact SUV with panoramic sunroof, ventilated front seats, Bose audio, Level-2 ADAS, and smooth IVT automatic transmission.",
        "image_file": "hyundai_creta_sx.jpg",
        "bg_color": "#2c3e50",
    },
    {
        "name": "Maruti Suzuki Swift ZXi+",
        "brand": "Maruti Suzuki",
        "model": "Swift ZXi+",
        "year": 2023,
        "color": "Pearl Metallic Lucent Orange",
        "registration_number": "BA-14-CHA-3321",
        "vehicle_type": VehicleType.CAR,
        "transmission": Transmission.MANUAL,
        "fuel_type": FuelType.PETROL,
        "engine_cc": 1197,
        "mileage_kmpl": Decimal("22.50"),
        "horsepower": 90,
        "torque_nm": Decimal("113.00"),
        "top_speed_kmph": 165,
        "seats": 5,
        "luggage_capacity_kg": Decimal("268.00"),
        "fuel_tank_capacity_l": Decimal("37.00"),
        "odometer_km": 16200,
        "price_per_day": Decimal("4000.00"),
        "price_per_hour": Decimal("600.00"),
        "security_deposit": Decimal("15000.00"),
        "has_ac": True,
        "has_bluetooth": True,
        "has_usb_charger": True,
        "pickup_location": "Maitighar, Kathmandu",
        "description": "Zippy, highly fuel-efficient hatchback with crisp handling, touch infotainment system with Apple CarPlay/Android Auto.",
        "image_file": "suzuki_swift.jpg",
        "bg_color": "#e65100",
    },
    {
        "name": "Tata Nexon EV Long Range",
        "brand": "Tata Motors",
        "model": "Nexon EV LR",
        "year": 2024,
        "color": "Pristine White",
        "registration_number": "BA-01-CHA-9090",
        "vehicle_type": VehicleType.CAR,
        "transmission": Transmission.AUTOMATIC,
        "fuel_type": FuelType.ELECTRIC,
        "battery_range_km": 465,
        "horsepower": 143,
        "torque_nm": Decimal("215.00"),
        "top_speed_kmph": 150,
        "seats": 5,
        "luggage_capacity_kg": Decimal("350.00"),
        "odometer_km": 7800,
        "price_per_day": Decimal("8000.00"),
        "price_per_hour": Decimal("1100.00"),
        "security_deposit": Decimal("25000.00"),
        "has_ac": True,
        "has_gps": True,
        "has_bluetooth": True,
        "has_usb_charger": True,
        "has_child_seat": True,
        "pickup_location": "Patan Durbar Square area, Lalitpur",
        "description": "Eco-friendly, whisper-quiet electric SUV featuring 40.5kWh battery pack, V2V and V2L charging capabilities, and high ground clearance.",
        "image_file": "tata_nexon_ev.jpg",
        "bg_color": "#00838f",
    },
    {
        "name": "Honda City ZX",
        "brand": "Honda",
        "model": "City ZX",
        "year": 2023,
        "color": "Radiant Red Metallic",
        "registration_number": "BA-11-CHA-7711",
        "vehicle_type": VehicleType.CAR,
        "transmission": Transmission.AUTOMATIC,
        "fuel_type": FuelType.PETROL,
        "engine_cc": 1498,
        "mileage_kmpl": Decimal("18.40"),
        "horsepower": 121,
        "torque_nm": Decimal("145.00"),
        "top_speed_kmph": 180,
        "seats": 5,
        "luggage_capacity_kg": Decimal("506.00"),
        "fuel_tank_capacity_l": Decimal("40.00"),
        "odometer_km": 14000,
        "price_per_day": Decimal("6500.00"),
        "price_per_hour": Decimal("900.00"),
        "security_deposit": Decimal("20000.00"),
        "has_ac": True,
        "has_gps": True,
        "has_bluetooth": True,
        "has_usb_charger": True,
        "pickup_location": "Naxal, Kathmandu",
        "description": "Executive luxury sedan with plush leather upholstery, electric sunroof, lane-watch camera, and unmatched rear passenger legroom.",
        "image_file": "honda_city_zx.jpg",
        "bg_color": "#b71c1c",
    },
    {
        "name": "Toyota Corolla Altis Hybrid",
        "brand": "Toyota",
        "model": "Corolla Altis Hybrid",
        "year": 2023,
        "color": "Super White",
        "registration_number": "BA-09-CHA-4411",
        "vehicle_type": VehicleType.CAR,
        "transmission": Transmission.AUTOMATIC,
        "fuel_type": FuelType.HYBRID,
        "engine_cc": 1798,
        "mileage_kmpl": Decimal("24.00"),
        "horsepower": 122,
        "torque_nm": Decimal("163.00"),
        "top_speed_kmph": 180,
        "seats": 5,
        "luggage_capacity_kg": Decimal("470.00"),
        "fuel_tank_capacity_l": Decimal("43.00"),
        "odometer_km": 18000,
        "price_per_day": Decimal("9000.00"),
        "price_per_hour": Decimal("1200.00"),
        "security_deposit": Decimal("25000.00"),
        "has_ac": True,
        "has_gps": True,
        "has_bluetooth": True,
        "has_usb_charger": True,
        "pickup_location": "Lazimpat, Kathmandu",
        "description": "Self-charging hybrid executive sedan delivering ultra-refined highway cruising and class-leading fuel economy.",
        "image_file": "toyota_corolla_hybrid.jpg",
        "bg_color": "#1565c0",
    },

    # ── Jeeps / 4x4s ───────────────────────────────────────────────────────
    {
        "name": "Mahindra Thar 4x4 LX Hard Top",
        "brand": "Mahindra",
        "model": "Thar LX 4WD",
        "year": 2023,
        "color": "Napoli Black",
        "registration_number": "BA-18-CHA-4004",
        "vehicle_type": VehicleType.JEEP,
        "transmission": Transmission.MANUAL,
        "fuel_type": FuelType.DIESEL,
        "engine_cc": 2184,
        "mileage_kmpl": Decimal("14.00"),
        "horsepower": 130,
        "torque_nm": Decimal("300.00"),
        "top_speed_kmph": 155,
        "seats": 4,
        "luggage_capacity_kg": Decimal("300.00"),
        "fuel_tank_capacity_l": Decimal("57.00"),
        "odometer_km": 13500,
        "price_per_day": Decimal("8500.00"),
        "price_per_hour": Decimal("1200.00"),
        "security_deposit": Decimal("25000.00"),
        "has_ac": True,
        "has_gps": True,
        "has_bluetooth": True,
        "has_usb_charger": True,
        "pickup_location": "Lakeside, Pokhara",
        "description": "True off-road beast with shift-on-the-fly 4x4 low-range gearbox, mechanical locking rear differential, and 226mm ground clearance for Muktinath & Upper Mustang expeditions.",
        "image_file": "mahindra_thar.jpg",
        "bg_color": "#212121",
    },
    {
        "name": "Mahindra Scorpio-N Z8L 4x4",
        "brand": "Mahindra",
        "model": "Scorpio-N Z8L",
        "year": 2024,
        "color": "Dazzling Silver",
        "registration_number": "BA-20-CHA-7700",
        "vehicle_type": VehicleType.JEEP,
        "transmission": Transmission.AUTOMATIC,
        "fuel_type": FuelType.DIESEL,
        "engine_cc": 2198,
        "mileage_kmpl": Decimal("13.50"),
        "horsepower": 175,
        "torque_nm": Decimal("400.00"),
        "top_speed_kmph": 175,
        "seats": 7,
        "luggage_capacity_kg": Decimal("460.00"),
        "fuel_tank_capacity_l": Decimal("57.00"),
        "odometer_km": 9200,
        "price_per_day": Decimal("11000.00"),
        "price_per_hour": Decimal("1500.00"),
        "security_deposit": Decimal("30000.00"),
        "has_ac": True,
        "has_gps": True,
        "has_bluetooth": True,
        "has_usb_charger": True,
        "has_child_seat": True,
        "pickup_location": "Kalanki, Kathmandu",
        "description": "Commanding 7-seater SUV with 4XPLOR terrain modes (Normal, Snow, Mud, Sand), Sony 12-speaker audio system, and robust ladder-frame chassis.",
        "image_file": "mahindra_scorpio_n.jpg",
        "bg_color": "#37474f",
    },
    {
        "name": "Toyota Fortuner 4x4 Legender",
        "brand": "Toyota",
        "model": "Fortuner Legender 4WD",
        "year": 2024,
        "color": "Platinum Pearl White with Black Roof",
        "registration_number": "BA-01-JA-9999",
        "vehicle_type": VehicleType.JEEP,
        "transmission": Transmission.AUTOMATIC,
        "fuel_type": FuelType.DIESEL,
        "engine_cc": 2755,
        "mileage_kmpl": Decimal("12.00"),
        "horsepower": 204,
        "torque_nm": Decimal("500.00"),
        "top_speed_kmph": 185,
        "seats": 7,
        "luggage_capacity_kg": Decimal("600.00"),
        "fuel_tank_capacity_l": Decimal("80.00"),
        "odometer_km": 11000,
        "price_per_day": Decimal("18000.00"),
        "price_per_hour": Decimal("2500.00"),
        "security_deposit": Decimal("50000.00"),
        "has_ac": True,
        "has_gps": True,
        "has_bluetooth": True,
        "has_usb_charger": True,
        "has_child_seat": True,
        "pickup_location": "Baluwatar, Kathmandu",
        "description": "The benchmark premium 4x4 SUV. Unshakeable durability, 500Nm torque, dual-zone climate control, and unmatched presence.",
        "image_file": "toyota_fortuner.jpg",
        "bg_color": "#0d47a1",
    },

    # ── Auto Rickshaws ─────────────────────────────────────────────────────
    {
        "name": "Bajaj RE Compact 4S Auto",
        "brand": "Bajaj",
        "model": "RE Compact 4S",
        "year": 2022,
        "color": "Classic Yellow & Green",
        "registration_number": "BA-1-HA-1234",
        "vehicle_type": VehicleType.AUTO_RICKSHAW,
        "transmission": Transmission.MANUAL,
        "fuel_type": FuelType.PETROL,
        "engine_cc": 198,
        "mileage_kmpl": Decimal("35.00"),
        "horsepower": 10,
        "torque_nm": Decimal("16.00"),
        "top_speed_kmph": 65,
        "seats": 4,
        "luggage_capacity_kg": Decimal("50.00"),
        "fuel_tank_capacity_l": Decimal("8.00"),
        "odometer_km": 28000,
        "price_per_day": Decimal("1800.00"),
        "price_per_hour": Decimal("300.00"),
        "security_deposit": Decimal("5000.00"),
        "pickup_location": "Bharatpur, Chitwan",
        "description": "Standard 3-wheeler auto rickshaw for local transport, sightseeing, or inner city commuting.",
        "image_file": "bajaj_re_compact.jpg",
        "bg_color": "#fbc02d",
    },
    {
        "name": "Mahindra Treo Electric Auto",
        "brand": "Mahindra",
        "model": "Treo",
        "year": 2024,
        "color": "Sky Blue & White",
        "registration_number": "BA-2-HA-5678",
        "vehicle_type": VehicleType.AUTO_RICKSHAW,
        "transmission": Transmission.AUTOMATIC,
        "fuel_type": FuelType.ELECTRIC,
        "battery_range_km": 130,
        "horsepower": 11,
        "torque_nm": Decimal("42.00"),
        "top_speed_kmph": 55,
        "seats": 4,
        "luggage_capacity_kg": Decimal("60.00"),
        "odometer_km": 6400,
        "price_per_day": Decimal("2000.00"),
        "price_per_hour": Decimal("350.00"),
        "security_deposit": Decimal("6000.00"),
        "has_usb_charger": True,
        "pickup_location": "Janakpur City Center",
        "description": "Zero-emission lithium-ion electric auto rickshaw with regenerative braking and super quiet operation.",
        "image_file": "mahindra_treo_ev.jpg",
        "bg_color": "#0288d1",
    },

    # ── Buses ──────────────────────────────────────────────────────────────
    {
        "name": "Force Traveller 3350 Luxury Mini Bus",
        "brand": "Force Motors",
        "model": "Traveller 3350",
        "year": 2023,
        "color": "Pearl White with Gold Striping",
        "registration_number": "BA-1-KHA-8822",
        "vehicle_type": VehicleType.BUS,
        "transmission": Transmission.MANUAL,
        "fuel_type": FuelType.DIESEL,
        "engine_cc": 2596,
        "mileage_kmpl": Decimal("11.50"),
        "horsepower": 115,
        "torque_nm": Decimal("350.00"),
        "top_speed_kmph": 110,
        "seats": 17,
        "luggage_capacity_kg": Decimal("800.00"),
        "fuel_tank_capacity_l": Decimal("70.00"),
        "odometer_km": 34000,
        "price_per_day": Decimal("14000.00"),
        "price_per_hour": Decimal("2000.00"),
        "security_deposit": Decimal("30000.00"),
        "has_ac": True,
        "has_gps": True,
        "has_bluetooth": True,
        "has_usb_charger": True,
        "pickup_location": "Balkhu, Kathmandu",
        "description": "17-passenger pushback luxury seating, high roof with individual AC louvers and reading lamps. Ideal for family trips, wedding parties, and corporate outings.",
        "image_file": "force_traveller.jpg",
        "bg_color": "#455a64",
    },
    {
        "name": "Tata Starbus Ultra 34-Seater Tour Bus",
        "brand": "Tata Motors",
        "model": "Starbus Ultra",
        "year": 2023,
        "color": "Royal Blue",
        "registration_number": "BA-2-KHA-9900",
        "vehicle_type": VehicleType.BUS,
        "transmission": Transmission.MANUAL,
        "fuel_type": FuelType.DIESEL,
        "engine_cc": 3783,
        "mileage_kmpl": Decimal("7.00"),
        "horsepower": 140,
        "torque_nm": Decimal("400.00"),
        "top_speed_kmph": 90,
        "seats": 34,
        "luggage_capacity_kg": Decimal("1800.00"),
        "fuel_tank_capacity_l": Decimal("160.00"),
        "odometer_km": 48000,
        "price_per_day": Decimal("24000.00"),
        "price_per_hour": Decimal("3500.00"),
        "security_deposit": Decimal("50000.00"),
        "has_ac": True,
        "has_gps": True,
        "has_usb_charger": True,
        "pickup_location": "Gongabu New Bus Park, Kathmandu",
        "description": "Full-size 34-seater intercity tour coach with air-suspension, microphone sound system, and expansive underbody luggage compartments.",
        "image_file": "tata_starbus.jpg",
        "bg_color": "#1a237e",
    },

    # ── Trucks ─────────────────────────────────────────────────────────────
    {
        "name": "Tata Ace Gold Mini Truck",
        "brand": "Tata Motors",
        "model": "Ace Gold Diesel+",
        "year": 2023,
        "color": "Arctic White",
        "registration_number": "BA-1-CHA-1122",
        "vehicle_type": VehicleType.TRUCK,
        "transmission": Transmission.MANUAL,
        "fuel_type": FuelType.DIESEL,
        "engine_cc": 702,
        "mileage_kmpl": Decimal("21.00"),
        "horsepower": 20,
        "torque_nm": Decimal("45.00"),
        "top_speed_kmph": 70,
        "seats": 2,
        "luggage_capacity_kg": Decimal("750.00"),
        "fuel_tank_capacity_l": Decimal("30.00"),
        "odometer_km": 21000,
        "price_per_day": Decimal("3000.00"),
        "price_per_hour": Decimal("500.00"),
        "security_deposit": Decimal("8000.00"),
        "pickup_location": "Teku Commercial Hub, Kathmandu",
        "description": "Nepal's favorite 'Chotta Hathi' mini utility truck with 750kg payload capacity. Perfect for shifting apartments, goods delivery, or cargo.",
        "image_file": "tata_ace_gold.jpg",
        "bg_color": "#546e7a",
    },
    {
        "name": "Mahindra Bolero Maxi Truck Plus",
        "brand": "Mahindra",
        "model": "Bolero Maxi Truck Plus",
        "year": 2024,
        "color": "Diamond White",
        "registration_number": "BA-2-CHA-3344",
        "vehicle_type": VehicleType.TRUCK,
        "transmission": Transmission.MANUAL,
        "fuel_type": FuelType.DIESEL,
        "engine_cc": 2523,
        "mileage_kmpl": Decimal("17.20"),
        "horsepower": 65,
        "torque_nm": Decimal("195.00"),
        "top_speed_kmph": 100,
        "seats": 2,
        "luggage_capacity_kg": Decimal("1200.00"),
        "fuel_tank_capacity_l": Decimal("45.00"),
        "odometer_km": 15000,
        "price_per_day": Decimal("4500.00"),
        "price_per_hour": Decimal("700.00"),
        "security_deposit": Decimal("12000.00"),
        "has_gps": True,
        "pickup_location": "Suryabinayak, Bhaktapur",
        "description": "Heavy duty commercial pickup truck with 1.2 Ton rated payload capacity, power steering, and reinforced suspension for rugged terrain transport.",
        "image_file": "mahindra_bolero_truck.jpg",
        "bg_color": "#3e2723",
    },
]


class Command(BaseCommand):
    help = "Seeds the database with a rich, realistic fleet of diverse vehicles across all vehicle types."

    def add_arguments(self, parser):
        parser.add_argument(
            "--clear",
            action="store_true",
            help="Delete existing vehicles and images before seeding.",
        )
        parser.add_argument(
            "--no-images",
            action="store_true",
            help="Skip generating sample vehicle image files.",
        )

    def handle(self, *args, **options):
        clear_old = options["clear"]
        skip_images = options["no_images"]

        if clear_old:
            self.stdout.write(self.style.WARNING("Clearing existing vehicles..."))
            Vehicle.objects.all().delete()
            self.stdout.write(self.style.SUCCESS("Existing vehicles deleted."))

        created_count = 0
        updated_count = 0

        today = date.today()
        reg_expiry = today + timedelta(days=365)
        ins_expiry = today + timedelta(days=180)

        for item in VEHICLES_SEED_DATA:
            image_file = item.pop("image_file", None)
            bg_color = item.pop("bg_color", "#2c3e50")

            reg_no = item["registration_number"]

            defaults = {
                **item,
                "registration_expiry": reg_expiry,
                "insurance_expiry": ins_expiry,
                "status": VehicleStatus.ACTIVE,
            }

            vehicle, created = Vehicle.objects.update_or_create(
                registration_number=reg_no,
                defaults=defaults,
            )

            if created:
                created_count += 1
            else:
                updated_count += 1

            # Handle primary sample image
            if not skip_images and image_file:
                image_rel_path = create_placeholder_image(
                    filename=image_file,
                    title=vehicle.name,
                    subtitle=f"{vehicle.brand} • {vehicle.get_vehicle_type_display()} • {vehicle.year}",
                    color_hex=bg_color,
                )

                if image_rel_path:
                    # Update or create the primary VehicleImage
                    VehicleImage.objects.update_or_create(
                        vehicle=vehicle,
                        is_primary=True,
                        defaults={
                            "image": image_rel_path,
                            "alt_text": f"Photo of {vehicle.name}",
                        },
                    )

        self.stdout.write(
            self.style.SUCCESS(
                f"\nSuccessfully seeded vehicles!\n"
                f"  Created: {created_count}\n"
                f"  Updated: {updated_count}\n"
                f"  Total vehicles in database: {Vehicle.objects.count()}\n"
            )
        )
