# Generated by Django 6.1 on 2026-08-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsewaRedrectUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_url', models.URLField()),
                ('failure_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='SucessURL',
        ),
    ]
