# Generated by Django 6.1 on 2026-09-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('full_refund', 'Full Refund'), ('partial_refund', 'Partial Refund'), ('ambiguous', 'Ambiguous'), ('not_found', 'Not Found'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
