# Generated by Django 6.1 on 2026-09-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={'ordering': ['-is_primary', 'created_at']},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='battery_range_km',
            field=models.PositiveIntegerField(blank=True, help_text='Range on full charge in km. Applicable only to EVs.', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_cc',
            field=models.PositiveIntegerField(blank=True, help_text='Engine displacement in cubic centimetres (CC). Leave blank for electric vehicles.', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_tank_capacity_l',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fuel tank capacity in litres. Leave blank for EVs.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_ac',
            field=models.BooleanField(default=False, help_text='Air conditioning available.'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_bluetooth',
            field=models.BooleanField(default=False, help_text='Bluetooth audio.'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_child_seat',
            field=models.BooleanField(default=False, help_text='Child/baby seat included.'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_gps',
            field=models.BooleanField(default=False, help_text='GPS navigation system.'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_usb_charger',
            field=models.BooleanField(default=False, help_text='USB charging port.'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='horsepower',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum power output in BHP/HP.', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='luggage_capacity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum luggage/load capacity in kilograms.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_rental_days',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of days allowed per booking. Leave blank for no limit.', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage_kmpl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fuel efficiency in km per litre (or km per charge for EVs).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='min_rental_days',
            field=models.PositiveIntegerField(default=1, help_text='Minimum number of days a renter must book.'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer_km',
            field=models.PositiveIntegerField(default=0, help_text='Current odometer reading in kilometres.'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pickup_location',
            field=models.CharField(blank=True, help_text='Address or landmark where the vehicle is available for pickup.', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rental rate. Optional.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(default='TEMP-REG', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Refundable security deposit amount.', max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='top_speed_kmph',
            field=models.PositiveIntegerField(blank=True, help_text='Top speed in km/h.', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='torque_nm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum torque in Newton-metres (Nm).', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Short description of the image for accessibility.', max_length=200),
        ),
    ]
