# Generated by Django 6.1 on 2026-08-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('cycle', 'Cycle'), ('scooter', 'Scooter'), ('motorcycle', 'Motorcycle'), ('auto_rickshaw', 'Auto Rickshaw'), ('car', 'Car'), ('jeep', 'Jeep'), ('bus', 'Bus'), ('truck', 'Truck')], default='motorcycle', max_length=50),
        ),
    ]
